server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dummyfun
    port: 3306
    username: 'username'
    password: 'password'
    driver-class-name: com.mysql.cj.jdbc.Driver
